name = "papermc"
type = "javascript"
account_id = "326bd0a4b72213bcf7f6cdff5e7b3313"
workers_dev = true
route = ""
zone_id = "528d8ede5e2c958e299793b84e68a89f"
compatibility_date = "2021-11-12"

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
